### ISSUE TITLE
Can't log into RetroAchievements

### ISSUE THREAD

**Issue by Mobeeuz** [retro-center/rcade_releases#23] opened 2023-01-30 10:13 UTC
When logging into RetroAchievements, the password is saved with additional characters added as can be seen via the retroarch.cfg file.

**Comment by Mobeeuz** [comment] 2023-02-01 06:23
For those with the same issue, you can SSH into your Legends cabinet and edit the file:
/rcade/resources/config/retroarch.cfg.overrides
to add the following code:
```
cheevos_username = "RETROACHIEVEMNETS USERNAME"
cheevos_password = "RETROACHIEVEMNETS PASSWORD"
```
and it will work...

**Comment by retro-center** [comment] 2023-04-01 03:52
I made some adjustments in 1.0.9 to try and fix this, but I was not able to reproduce this. 
can you please let me know if it’s resolved after upgrading to 1.0.9?
Thank you for reporting!

**Comment by Mobeeuz** [comment] 2023-04-02 18:24
This issue only appeared once. Seems you have to flash the drive multiple times before you get a good write as other issues randomly appear as well. It was reported on the Discord channel. I will wait for the next full image release before I roll the dice with another flash. My only current issue is single game overrides not saving/loading (has worked in previous flashes) which the 1.09 update did not fix, and I don't want to invite bigger problems.

**Comment by retro-center** [comment] 2023-06-27 12:53
There's no current reports of any issues retroachievements or with game overrides. @Mobeeuz can you confirm if you are still experiencing these issues? If so - would love a support archive sent over after reproducing the issue with debug logging enabled.

**Comment by Mobeeuz** [comment] 2023-06-27 13:52
I did a full flash with the 1.10 release. So far no issues.

**Comment by retro-center** [comment] 2023-06-27 19:53
Great! Thanks for the update, closing this issue but feel free to re-open if you run into it again.

**Closed by retro-center** 2023-06-27 19:53 UTC
