### ISSUE TITLE
8BitDo Pro 2 controllers / TZ in EmulationStation

### ISSUE THREAD

**Issue by geekboy01** [retro-center/rcade_releases#15] opened 2022-10-17 23:08 UTC
R-Cade release: 1.0.7
HW: RockPro 64

Issue/feature

I run 8BitDo Pro 2 controllers which sync and function great.  however I was wondering if there was a way to get the 'Controller ID' (ie. the light on the controller like on PS2) to show which controller number it is.  ie. first light is controller 1, second light is controller 2 etc.  Currently all of them when synced will show controller 1 on the the controller itself.

Issue:

The other issue is when in ES and showing the time.  it shows the time the system has however (and it could be due to me being blind) i can't seem to get it to my timezone.  I can set the TZ in Kodi and it will show current time but in ES I can't seem to find a way to change the TZ so it will show the proper time.

Question:

Is GameCube/Wii emulation on the roadmap?

**Comment by retro-center** [comment] 2022-10-21 12:26
@geekboy01 thank you for reaching out!

The player number LEDs on the gamepad are something that's controlled in the driver. I don't have an 8bitDo Pro2 to test with, but if you copy the output of your dmesg into dpaste and link it here I can confirm what driver the gamepad is using and see if this might be possible at some point. This same issue exists for a number of other controllers, such as xpad. 

The time and timezone are automatically set in RCade as soon as the network comes online. It reaches out to a time server to set them based on your IP address. I have seen some cases where the network can take too long to connect and the timezone isn't set, and I have a fix for that coming in the next release - 1.0.8

GameCube / Wii are provided by the dolphin emulator. This emulator requires a full 64-bit userspace, and currently RCade uses a 32bit userspace. There are some great enhancements coming in the future, and with the mainline kernel finally receiving support the proper video acceleration I should be able to upgrade to that hopefully sometime early-mid 2023. At that time it I will evaluate performance of a full 64-bit OS and if everything works well then we will be able to potentially add the dolphin emulator, as well as a few others.

I'll leave this issue open until the next release and close it for the timezone fix after that. If you do continue to encounter that issue, please do re-open the issue!

**Comment by geekboy01** [comment] 2022-10-21 21:15
Much appreciate the explanations on the different areas.

Output from dmesg:  https://dpaste.com/334F8B4RE

**Comment by retro-center** [comment] 2022-10-22 02:48
hid-generic 0005:2DC8:6006.0003: input,hidraw2: BLUETOOTH HID v1.00 Gamepad [8BitDo Pro 2] on 43:45:c5:00:1f:ac
Looks like it’s using the generic driver, I’ll see if I can find one I can port with intended support for this gamepad. Thanks for letting me know!

**Comment by retro-center** [comment] 2023-02-17 18:31
@geekboy01 can you confirm the time and timezone is reliably being set now in v1.0.8?

I haven't been able to find a driver for that 8bitdo that sets the LEDs yet, but I'll keep looking! Feel free to open a separate feature-request for that if you'd like. :)

**Comment by geekboy01** [comment] 2023-02-17 21:37
Thanks for checking mate.  Its not a big deal at all and maybe at some
point I'll open a request.  Thank you for the great work you've already
done.

**Comment by retro-center** [comment] 2023-03-17 21:25
Closing this out! But please let me know if you see any issues with the time or timezone not setting properly

**Closed by retro-center** 2023-03-17 21:25 UTC
